import React from "react";
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';

const COLORS = {
  accentGreen: '#A8E6CF',
  accentBlue: '#B3E5FC',
  background: '#fff',
  card: '#fff',
  accentBrown: '#D7CCC8',
  black: '#111',
};

const CarbonFootprintCalculator = () => {
  const [distance, setDistance] = React.useState('');
  const [plastic, setPlastic] = React.useState('');
  const [result, setResult] = React.useState(null);

  // Simple formula: distance * 0.21 + plastic * 6 (example)
  const handleCalculate = (e) => {
    e.preventDefault();
    const d = parseFloat(distance) || 0;
    const p = parseFloat(plastic) || 0;
    const value = d * 0.21 + p * 6;
    setResult(value.toFixed(2));
  };

  return (
    <Box
      sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        py: 4,
        px: 3,
      }}
    >
      <Card sx={{ 
        width: '100%', 
        borderRadius: 5, 
        boxShadow: '0 10px 30px rgba(0,0,0,0.15)', 
        background: COLORS.card, 
        p: 3 
      }}>
        <CardContent sx={{ p: 4 }}>
          <Typography variant="h4" sx={{ fontWeight: 800, color: COLORS.green, mb: 4, textAlign: 'center', letterSpacing: 0.5 }}>
            Carbon Footprint Calculator
          </Typography>
          
          <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, gap: 3, alignItems: 'stretch' }}>
            {/* Left: Image */}
            <Box sx={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <img
                src={"https://media.istockphoto.com/id/1441625773/vector/co2-footprint-vector-icon.jpg?s=612x612&w=0&k=20&c=HrPur_ku2kgpSzCoKSNEmqWONQogsZFYP0M7z0z9Js0="}
                alt="Carbon Footprint"
                style={{ width: '100%', maxHeight: 200, objectFit: 'contain', borderRadius: 8 }}
              />
            </Box>
            
            {/* Right: Calculator */}
            <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 2 }}>
              <Box component="form" onSubmit={handleCalculate} sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <TextField 
                  label="Distance Travelled (km)" 
                  value={distance} 
                  onChange={e => setDistance(e.target.value)} 
                  fullWidth 
                  variant="outlined" 
                  size="small"
                  sx={{ background: COLORS.background, borderRadius: 2 }} 
                />
                <TextField 
                  label="Plastic Used (kg)" 
                  value={plastic} 
                  onChange={e => setPlastic(e.target.value)} 
                  fullWidth 
                  variant="outlined" 
                  size="small"
                  sx={{ background: COLORS.background, borderRadius: 2 }} 
                />
                <Button 
                  type="submit" 
                  variant="contained" 
                  fullWidth 
                  sx={{
                    borderRadius: 2,
                    fontSize: 14,
                    fontWeight: 600,
                    py: 1,
                    background: COLORS.accentGreen,
                    color: '#333',
                    boxShadow: 'none',
                    textTransform: 'none',
                    '&:hover': {
                      background: COLORS.accentBlue,
                      color: '#222',
                    },
                  }}
                >
                  Calculate
                </Button>
              </Box>
              
              {result !== null && (
                <Box sx={{ p: 2, borderRadius: 2, background: COLORS.accentBlue, color: COLORS.black, fontWeight: 600, textAlign: 'center', fontSize: 16, boxShadow: '0 1px 6px rgba(0,0,0,0.04)' }}>
                  Your Carbon Footprint: {result} kg CO₂
                </Box>
              )}
            </Box>
          </Box>
          
          <Box sx={{ mt: 3, p: 2, borderRadius: 2, background: 'rgba(179, 229, 252, 0.1)', border: `1px solid ${COLORS.accentBlue}` }}>
            <Typography variant="body2" sx={{ color: COLORS.black, fontSize: 12, mb: 1 }}>
              According to the United Nations, a carbon footprint is the total amount of greenhouse gases generated by our actions. Reducing your carbon footprint helps combat climate change.
            </Typography>
            <a 
              href="https://www.un.org/en/actnow/ten-actions" 
              target="_blank" 
              rel="noopener noreferrer" 
              style={{ 
                color: COLORS.green, 
                textDecoration: 'underline', 
                fontWeight: 600,
                fontSize: '11px'
              }}
            >
              Learn more from the United Nations →
            </a>
          </Box>
        </CardContent>
      </Card>
    </Box>
  );
};

export default CarbonFootprintCalculator; 