import React from "react";
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import CarbonFootprintCalculator from './CarbonFootprintCalculator';

const COLORS = {
  black: '#111',
  background: '#fff',
  card: '#fff',
  accentGreen: '#A8E6CF',
  accentBlue: '#B3E5FC',
  accentBrown: '#D7CCC8',
};

const CarbonFootprintRow = () => {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: { xs: 'column', md: 'row' },
        gap: 4,
        my: 4,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'stretch',
        background: COLORS.background,
        py: 2,
      }}
    >
      <Card sx={{ flex: 1, minWidth: 320, maxWidth: 600, mb: { xs: 4, md: 0 }, boxShadow: '0 4px 24px rgba(0,0,0,0.08)', borderRadius: 4, display: 'flex', flexDirection: 'column', background: COLORS.card, p: 2 }}>
        <CardContent sx={{ flex: 1, display: 'flex', flexDirection: 'column', p: 0 }}>
          <CarbonFootprintCalculator />
        </CardContent>
      </Card>
      <Card sx={{ flex: 1, minWidth: 320, maxWidth: 600, boxShadow: '0 4px 24px rgba(0,0,0,0.08)', borderRadius: 4, display: 'flex', flexDirection: 'column', background: COLORS.card, p: 2 }}>
        <CardContent sx={{ flex: 1, display: 'flex', flexDirection: 'column', p: 3 }}>
          <Typography variant="h6" sx={{ fontWeight: 700, color: COLORS.accentBrown, mb: 2 }}>
            About Carbon Footprint
          </Typography>
          <Typography variant="body2" sx={{ mb: 2, color: COLORS.black }}>
            A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It is usually measured in equivalent tons of CO₂. Reducing your carbon footprint helps combat climate change and can be achieved by minimizing energy use, reducing waste, and making sustainable choices.
          </Typography>
          <Typography variant="caption" sx={{ color: COLORS.accentBlue }}>
            Source: <a href="https://www.nationalgeographic.com/environment/article/carbon-footprint" target="_blank" rel="noopener noreferrer" style={{ color: COLORS.accentBlue, textDecoration: 'underline' }}>National Geographic</a>
          </Typography>
        </CardContent>
      </Card>
    </Box>
  );
};

export default CarbonFootprintRow; 